spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: rag_user
    password: rag_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

openai:
  api-key: sk-xxx-local
  model: gpt-3.5-turbo