spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: rag_user
    password: rag_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariPool-1
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 600000
      connection-timeout: 30000
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: validate   # 스키마 수동 관리
    show-sql: true         # 콘솔에 SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true
        connection.provider_disables_autocommit: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.connections.pooling: warn  # 연결 정보 로그 레벨 최소화
    org.springframework.jdbc.datasource: warn

openai:
  api-key: sk-xxx-local
  model: gpt-3.5-turbo

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html